name: check

on:
  push:
    branches: ["{{ git.branch }}"]
  pull_request:
    branches: ["**"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        node-version: ["22", "24"]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - uses: actions/setup-node@v4
        name: Configure Node
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - run: yarn
        name: Install dependencies

      - run: yarn exec -- prettier --check .
        name: Format
        if: ${{ matrix.node-version == '24' }}

      - run: yarn type-check
        name: Check types
        if: ${{ matrix.node-version == '24' }}

      - run: yarn test
        name: Test
