name: check

on:
  push:
    branches: ["{{ git.branch }}"]
  pull_request:
    branches: ["**"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - uses: erlef/setup-beam@v1
        name: Configure Gleam
        with:
          otp-version: "28.0"
          gleam-version: "1.12"

      - run: gleam format --check
        name: Format

      - run: gleam test
        name: Test
