name: main

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - uses: erlef/setup-beam@v1
        name: Prepare
        with:
          otp-version: "26.2"
          gleam-version: "1.1"

      - run: gleam format --check
        name: Format

      - run: gleam test
        name: Test
