name: Release

on:
  push:
    tags: ["v*.*.*"]

jobs:
  publish:
    name: Publish

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - run: |
          version="v$(cat gleam.toml | grep -m 1 "version" | sed -r "s/version *= *\"([[:digit:].]+)\"/\1/")"
          if [ "$version" != "${{ github.ref_name }}" ]; then
            echo "tag ${{ github.ref_name }} does not match version $version in gleam.toml"
            exit 1
          fi
        name: Verify version

      - uses: erlef/setup-beam@v1
        name: Configure Gleam
        with:
          otp-version: "28.0"
          gleam-version: "1.12"

      - run: gleam test
        name: Test

      - run: gleam publish -y
        name: Publish
        env:
          HEXPM_USER: ${{ secrets.HEX_USERNAME }}
          HEXPM_PASS: ${{ secrets.HEX_PASSWORD }}

      - uses: softprops/action-gh-release@v1
        name: Release
