name: Check

on:
  push:
    branches: ["{{ git.branch }}"]
  pull_request:
    branches: ["**"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  conformance:
    name: Conformance

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - uses: crate-ci/typos@v1
        name: Spellcheck

      - uses: actions/setup-go@v5
        name: Configure Go

      - run: |
          go fmt ./...
          git diff --exit-code
        name: Format

      - run: go vet ./...
        name: Lint

      - run: go test ./...
        name: Test
