name: main

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v3
        name: Prepare
        with:
          go-version: ^1.22

      - run: |
          go fmt ./...
          git diff --exit-code
        name: Check

      - run: go vet ./...
        name: Check

      - run: go test
        name: Test
