edition = "2024"

hard_tabs = true
max_width = 80
tab_spaces = 2
use_small_heuristics = "Max"
# nightly only
# group_imports = "One" # https://github.com/rust-lang/rustfmt/issues/5083
# imports_granularity = "Item" # https://github.com/rust-lang/rustfmt/issues/4991
