name = "{{ name }}"
version = "0.0.0"
licences = ["MIT"]
description = ""
repository = { type = "github", user = "{{ github.owner }}", repo = "{{ name }}" }

[dependencies]
gleam_stdlib = ">= 0.36.0 and < 1.0.0"

[dev-dependencies]
gleeunit = "~> 1.0"
