name = "{{name}}"
version = "0.0.0"
licences = ["MIT"]
description = ""
repository = { type = "github", user = "aslilac", repo = "{{name}}" }

[dependencies]
gleam_stdlib = "~> 0.25"

[dev-dependencies]
gleeunit = "~> 0.7"
