name = "{{ name }}"
version = "0.0.0"
licences = ["MIT"]
description = ""
repository = { type = "github", user = "{{ github.owner }}", repo = "{{ name }}" }
gleam = ">= 1.12.0"

[dependencies]
gleam_stdlib = ">= 0.40.0 and < 2.0.0"

[dev-dependencies]
gleeunit = "~> 1.2"
