name: check

on:
  push:
    branches: ["{{ git.branch }}"]
  pull_request:
    branches: ["**"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - uses: actions/cache@v4
        name: Configure cache
        with:
          path: |
            ~/.cargo/
            ./build/
          key: test-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: test-cargo-

      - run: cargo test
        name: Test

  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - uses: actions/cache@v4
        name: Configure cache
        with:
          path: |
            ~/.cargo/
            ./build/
          key: lint-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: lint-cargo-

      - run: cargo fmt -- --check
        name: Format

      - run: cargo clippy
        name: Lint
