name: release

on:
  push:
    tags: ["v*.*.*"]

jobs:
  check:
    runs-on: ubuntu-latest
    name: Check

    steps:
      - uses: actions/checkout@v3
        name: Checkout

      - run: |
          version="v$(cat Cargo.toml | grep -m 1 "version" | sed -r "s/version *= *\"([[:digit:].]+)\"/\1/")"
          if [ "$version" != "${{ github.ref_name }}" ]; then
            echo "tag ${{ github.ref_name }} does not match version $version in Cargo.toml"
            exit 1
          fi
        name: Version

      - uses: actions/cache@v3
        name: Cache
        with:
          path: |
            ~/.cargo/
            ./build/
          key: publish-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: publish-cargo-

      - run: cargo test
        name: Test

  publish:
    runs-on: ubuntu-latest
    name: crates.io
    needs:
      - check

    steps:
      - uses: actions/checkout@v3
        name: Checkout

      - uses: actions/cache@v3
        name: Cache
        with:
          path: |
            ~/.cargo/
            ./build/
          key: publish-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: publish-cargo-

      - run: cargo publish
        name: Publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

  release:
    strategy:
      fail-fast: false
      matrix:
        release:
          # TODO: Figure out how to "setup pkg-config for cross-compilation"
          # - os: ubuntu-latest
          #   target: aarch64-unknown-linux-gnu
          #   executable: {{ name }}

          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            executable: {{ name }}

          - os: windows-latest
            target: aarch64-pc-windows-msvc
            executable: {{ name }}.exe

          - os: windows-latest
            target: x86_64-pc-windows-msvc
            executable: {{ name }}.exe

          - os: macos-latest
            target: aarch64-apple-darwin
            executable: {{ name }}

          - os: macos-latest
            target: x86_64-apple-darwin
            executable: {{ name }}

    runs-on: ${{ matrix.release.os }}
    name: ${{ matrix.release.target }}
    needs:
      - check

    steps:
      - uses: actions/checkout@v3
        name: Checkout

      - uses: actions/cache@v3
        name: Cache
        with:
          path: |
            ~/.cargo/
            ./build/
          key: release-${{ matrix.release.target }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: release-${{ matrix.release.target }}-cargo-

      - run: rustup target add ${{ matrix.release.target }}
        name: Prepare — ${{ matrix.release.target }}

      - run: cargo build --target ${{ matrix.release.target }} --release
        name: Build — ${{ matrix.release.target }}

      # Create .tar.gz files for Linux and macOS
      - run: tar -a -cf {{ name }}-${{ github.ref_name }}-${{ matrix.release.target }}.tar.gz ${{ matrix.release.executable }}
        name: Package (tar) — ${{ matrix.release.target }}
        working-directory: ./build/${{ matrix.release.target }}/release/
        if: ${{ !startsWith(matrix.release.os, 'windows') }}

      # Create .zip files for Linux and macOS
      - run: zip -r {{ name }}-${{ github.ref_name }}-${{ matrix.release.target }}.zip ${{ matrix.release.executable }}
        name: Package (zip) — ${{ matrix.release.target }}
        working-directory: ./build/${{ matrix.release.target }}/release/
        if: ${{ !startsWith(matrix.release.os, 'windows') }}

      # Create .zip files for Windows
      - run: Compress-Archive ${{ matrix.release.executable }} -DestinationPath {{ name }}-${{ github.ref_name }}-${{ matrix.release.target }}.zip
        name: Package (zip) — ${{ matrix.release.target }}
        working-directory: ./build/${{ matrix.release.target }}/release/
        if: ${{ startsWith(matrix.release.os, 'windows') }}

      # Upload archives to a Github release for this version
      - uses: softprops/action-gh-release@v1
        name: Publish
        with:
          files: ./build/${{ matrix.release.target }}/release/{{ name }}-${{ github.ref_name }}-${{ matrix.release.target }}.*

      # We don't want the archives to be stored in the cache of the build directory
      - run: rm {{ name }}-${{ github.ref_name }}-${{ matrix.release.target }}.*
        name: Cleanup
        working-directory: ./build/${{ matrix.release.target }}/release/
